CREATE TABLE "APP".BOOK (
  "ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"NAME" VARCHAR(30) NOT NULL,
	"AUTHOR" VARCHAR(30) NOT NULL,
	"PUBLISHER" VARCHAR(30) NOT NULL,
	"LANGUAGE" VARCHAR(30) NOT NULL,
	"GENRE" VARCHAR(30) NOT NULL,
	"YEAR_PUBLICATION" INTEGER NOT NULL,
	"QUANTITY" INTEGER NOT NULL,
	"PRICE" FLOAT NOT NULL
);

CREATE TABLE "APP".BOOKLIST (
	"ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"QUANTITY" INTEGER NOT NULL,
	"LIST_VALUE" FLOAT NOT NULL,
	"ISBN" INTEGER NOT NULL,
	"SALE_ID" INTEGER NOT NULL
);

CREATE TABLE "APP".SALE (
	"ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"VALUE" FLOAT not null,
	"CLIENT" INTEGER not null
);

CREATE TABLE "APP".USERS (
	"ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"EMAIL" VARCHAR(30) not null,
	"USERNAME" VARCHAR(30) not null,
	"PASSWORD" VARCHAR(30) not null,
	"TYPE" INTEGER not null
);
